export const passwordOptions = [
  {
    shortName: "Phrase Initials",
    label: "Use the first letter of each word from a phrase you create.",
    algo: "phraseInitials",
    type: "text",
    placeholder: "Cats love climbing tall trees",
  },
  {
    shortName: "Random Book Page Digits",
    label: "Enter a page number from a random book and use a number sequence from it.",
    algo: "bookPageDigits",
    type: "number",
    placeholder: "347",
  },
  {
    shortName: "Three Word Syllables",
    label: "Enter three words and combine short syllables from each.",
    algo: "threeWordSyllables",
    type: "text",
    placeholder: "elephant umbrella mountain",
  },
  {
    shortName: "Significant Day Number",
    label: "Enter a day of month that matters to you.",
    algo: "significantDay",
    type: "number",
    placeholder: "21",
  },
  {
    shortName: "Home Window Count",
    label: "Enter the number of windows in your home.",
    algo: "windowCount",
    type: "number",
    placeholder: "12",
  },
  {
    shortName: "Interesting Word Length",
    label: "Enter an obscure word; we use its letter count.",
    algo: "interestingWordLength",
    type: "text",
    placeholder: "serendipity",
  },
  {
    shortName: "Street Name Trigrams",
    label: "Enter three street names separated by commas; we use first 3 letters of each.",
    algo: "streetNameTrigrams",
    type: "text",
    placeholder: "Maple, Cedar, Oak",
  },
  {
    shortName: "Made-up Secret Sequence",
    label: "Enter a made-up word or phrase only you would know.",
    algo: "secretSequence",
    type: "text",
    placeholder: "ziltoid alpha",
  },
  {
    shortName: "Bed-to-Door Steps",
    label: "Enter your step count from bed to front door.",
    algo: "bedToDoorSteps",
    type: "number",
    placeholder: "37",
  },
  {
    shortName: "Two-Language Mix",
    label: "Enter two words from two languages separated by comma.",
    algo: "twoLanguageMix",
    type: "text",
    placeholder: "hola, bonjour",
  },
  {
    shortName: "Constant Digits",
    label: "Enter digits from a meaningful constant/ratio.",
    algo: "constantDigits",
    type: "text",
    placeholder: "314159",
  },
  {
    shortName: "Keystroke Pattern",
    label: "Enter a repeated keyboard pattern.",
    algo: "keystrokePattern",
    type: "text",
    placeholder: "qweqwe",
  },
  {
    shortName: "Album Count x2",
    label: "Enter photo count from an album; we multiply by 2.",
    algo: "albumCountTimesTwo",
    type: "number",
    placeholder: "88",
  },
  {
    shortName: "Invented Anagram",
    label: "Enter an invented word/phrase; we create an anagram.",
    algo: "inventedAnagram",
    type: "text",
    placeholder: "orbit lantern",
  },
  {
    shortName: "Room Object Count",
    label: "Enter one object count from a room.",
    algo: "roomObjectCount",
    type: "number",
    placeholder: "23",
  },
  {
    shortName: "Made-up Character + Random",
    label: "Enter a made-up character name; we add random digits.",
    algo: "characterPlusRandom",
    type: "text",
    placeholder: "Varko",
  },
  {
    shortName: "Productive Hours",
    label: "Enter hours that represent a memorable day.",
    algo: "productiveHours",
    type: "number",
    placeholder: "11",
  },
  {
    shortName: "Alphabet Position Code",
    label: "Enter a word; we map letters to alphabet positions.",
    algo: "alphabetPositionCode",
    type: "text",
    placeholder: "code",
  },
  {
    shortName: "Reversed Event Date",
    label: "Enter an event date and we reverse its digits.",
    algo: "reversedEventDate",
    type: "date",
  },
  {
    shortName: "Unread Email Count",
    label: "Enter your unread email count.",
    algo: "unreadEmailCount",
    type: "number",
    placeholder: "41",
  },
  {
    shortName: "Lyric Initials",
    label: "Enter a lyric line and use first letters.",
    algo: "lyricInitials",
    type: "text",
    placeholder: "we all live in a yellow submarine",
  },
  {
    shortName: "Book Page Count",
    label: "Enter page count from a meaningful book.",
    algo: "bookPageCount",
    type: "number",
    placeholder: "274",
  },
  {
    shortName: "Stopwatch Digits",
    label: "Enter a stopwatch time and use the digits.",
    algo: "stopwatchDigits",
    type: "text",
    placeholder: "03:47.21",
  },
  {
    shortName: "Inside Joke Acronym",
    label: "Enter inside-joke phrase and use initials.",
    algo: "insideJokeAcronym",
    type: "text",
    placeholder: "pizza before project launch",
  },
  {
    shortName: "Non-English Trigram",
    label: "Enter a non-English word and use first 3 letters.",
    algo: "nonEnglishTrigram",
    type: "text",
    placeholder: "amour",
  },
  {
    shortName: "Frequent Time Code",
    label: "Enter a frequently noticed time.",
    algo: "frequentTimeCode",
    type: "time",
  },
  {
    shortName: "Keyboard Pattern + Random",
    label: "Enter a keyboard pattern; we append random digits.",
    algo: "keyboardPatternPlusRandom",
    type: "text",
    placeholder: "zxc",
  },
  {
    shortName: "Key Count",
    label: "Enter number of keys on a keyboard/instrument.",
    algo: "keyCount",
    type: "number",
    placeholder: "88",
  },
  {
    shortName: "Photo Name Initials",
    label: "Enter names in a photo separated by commas; we use initials.",
    algo: "photoNameInitials",
    type: "text",
    placeholder: "Anna, Ben, Carlos",
  },
  {
    shortName: "Recent Street Initials",
    label: "Enter recent street names separated by commas; use initials.",
    algo: "recentStreetInitials",
    type: "text",
    placeholder: "Pine Street, Lake Road, Elm Avenue",
  },
];
