export const passwordOptions = [
  {
    shortName: "Special Characters",
    label: "Pick one or more symbols. If none are selected, 1-3 random symbols are used.",
    algo: "specialCharacterSelector",
    type: "symbol-multi",
    symbols: ['!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+', '-', '=', '?'],
  },
  {
    shortName: "Phrase Initials",
    label: "Use the first letter of each word from a phrase you create.",
    algo: "phraseInitials",
    type: "text",
    placeholder: "Cats love climbing tall trees",
  },
  {
    shortName: "Significant Day Number",
    label: "Enter a day of month that matters to you.",
    algo: "significantDay",
    type: "number",
    placeholder: "21",
  },
  {
    shortName: "Interesting Word Length",
    label: "Enter an obscure word; we use its letter count.",
    algo: "interestingWordLength",
    type: "text",
    placeholder: "serendipity",
  },
  {
    shortName: "Street Name Trigrams",
    label: "Enter three street names separated by commas; we use first 3 letters of each.",
    algo: "streetNameTrigrams",
    type: "text",
    placeholder: "Maple, Cedar, Oak",
  },
  {
    shortName: "Made-up Secret Sequence",
    label: "Enter a made-up word or phrase only you would know.",
    algo: "secretSequence",
    type: "text",
    placeholder: "ziltoid alpha",
  },
  {
    shortName: "Constant Digits",
    label: "Enter digits from a meaningful constant/ratio.",
    algo: "constantDigits",
    type: "text",
    placeholder: "314159",
  },
  {
    shortName: "Keystroke Pattern",
    label: "Enter a repeated keyboard pattern.",
    algo: "keystrokePattern",
    type: "text",
    placeholder: "qweqwe",
  },
  {
    shortName: "Made-up Character + Random",
    label: "Enter a made-up character name; we add random digits.",
    algo: "characterPlusRandom",
    type: "text",
    placeholder: "Varko",
  },
  {
    shortName: "Productive Hours",
    label: "Enter hours that represent a memorable day.",
    algo: "productiveHours",
    type: "number",
    placeholder: "11",
  },
  {
    shortName: "Reversed Event Date",
    label: "Enter an event date and we reverse its digits.",
    algo: "reversedEventDate",
    type: "date",
  },
  {
    shortName: "Lyric Initials",
    label: "Enter a lyric line and use first letters.",
    algo: "lyricInitials",
    type: "text",
    placeholder: "we all live in a yellow submarine",
  },
  {
    shortName: "Book Page Count",
    label: "Enter page count from a meaningful book.",
    algo: "bookPageCount",
    type: "number",
    placeholder: "274",
  },
  {
    shortName: "Inside Joke Acronym",
    label: "Enter inside-joke phrase and use initials.",
    algo: "insideJokeAcronym",
    type: "text",
    placeholder: "pizza before project launch",
  },
  {
    shortName: "Non-English Trigram",
    label: "Enter a non-English word and use first 3 letters.",
    algo: "nonEnglishTrigram",
    type: "text",
    placeholder: "amour",
  },
  {
    shortName: "Frequent Time Code",
    label: "Enter a frequently noticed time.",
    algo: "frequentTimeCode",
    type: "time",
  },
  {
    shortName: "Keyboard Pattern + Random",
    label: "Enter a keyboard pattern; we append random digits.",
    algo: "keyboardPatternPlusRandom",
    type: "text",
    placeholder: "zxc",
  },
  {
    shortName: "Photo Name Initials",
    label: "Enter names in a photo separated by commas; we use initials.",
    algo: "photoNameInitials",
    type: "text",
    placeholder: "Anna, Ben, Carlos",
  },
  {
    shortName: "Recent Street Initials",
    label: "Enter recent street names separated by commas; use initials.",
    algo: "recentStreetInitials",
    type: "text",
    placeholder: "Pine Street, Lake Road, Elm Avenue",
  },
];
