export const passwordOptions = [
  {
    shortName: 'Special Characters',
    label: 'Pick one or more symbols. If none are selected, 1-3 random symbols are used.',
    explanation: 'Use this to guarantee symbol coverage. You can select any number of symbols, or leave it blank for random symbols.',
    algo: 'specialCharacterSelector',
    type: 'symbol-multi',
    symbols: ['!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+', '-', '=', '?'],
  },
  {
    shortName: 'Phrase Initials',
    label: 'Enter a phrase and use the first letter from each word.',
    explanation: 'Example: "Cats love climbing tall trees" becomes "ClctT".',
    algo: 'phraseInitials',
    type: 'text',
    placeholder: 'Cats love climbing tall trees',
  },
  {
    shortName: 'Street You Lived On Before',
    label: 'Enter a previous street name.',
    explanation: 'We extract a short stable segment from a street you remember well.',
    algo: 'streetLivedBefore',
    type: 'text',
    placeholder: 'Maple Street',
  },
  {
    shortName: 'Reversed Year of a Special Event',
    label: 'Enter a year tied to an important event.',
    explanation: 'Example: "2018" becomes "8102".',
    algo: 'reversedSpecialEventYear',
    type: 'number',
    placeholder: '2018',
  },
  {
    shortName: 'Close Person Initials',
    label: 'Enter the name of a close person.',
    explanation: 'We use first letters of each word in the name.',
    algo: 'closePersonInitials',
    type: 'text',
    placeholder: 'Alex Marie Johnson',
  },
  {
    shortName: 'Famous Person Initials',
    label: 'Enter a famous person name.',
    explanation: 'We use first letters of each word in the name.',
    algo: 'famousPersonInitials',
    type: 'text',
    placeholder: 'Taylor Swift',
  },
  {
    shortName: 'Special Date',
    label: 'Pick a special date and choose output format.',
    explanation: 'Format A: 01/15/25 -> 11525. Format B: Jan1525.',
    algo: 'specialDate',
    type: 'special-date',
  },
  {
    shortName: 'Significant Day Number',
    label: 'Enter a day of month that matters to you.',
    explanation: 'Simple numeric anchor that is easy to recall.',
    algo: 'significantDay',
    type: 'number',
    placeholder: '21',
  },
  {
    shortName: 'Constant Digits',
    label: 'Enter digits from a meaningful constant or ratio.',
    explanation: 'Adds compact numeric complexity from a memorable sequence.',
    algo: 'constantDigits',
    type: 'text',
    placeholder: '314159',
  },
  {
    shortName: 'Song Name',
    label: 'Enter a song name. One or two words are used directly; longer names use initials.',
    explanation: 'Examples: "Numb" -> "Numb", "Bohemian Rhapsody" -> "BohemianRhapsody", "Stairway to Heaven" -> "sth".',
    algo: 'lyricInitials',
    type: 'text',
    placeholder: 'Stairway to Heaven',
  },
  {
    shortName: 'Frequent Time Code',
    label: 'Enter a frequently noticed time.',
    explanation: 'Example: 11:11 -> 1111.',
    algo: 'frequentTimeCode',
    type: 'time',
  },
];
